import type { VisualProfile } from "@/lib/visual-production/visual-profile";

export const editorialCoverV2: VisualProfile = {
  id: "editorial-cover-v2",
  version: 1,
  label: "Editorial Cover V2",
  description: "Locked premium editorial cover composition with code-rendered typography and a single dominant artwork field.",
  layout: {
    canvasWidth: 1600,
    canvasHeight: 2400,
    aspectRatio: "2:3",
    safeMargin: 96,
    mastheadBounds: { x: 120, y: 72, width: 1360, height: 160 },
    issueNumberBounds: { x: 656, y: 222, width: 288, height: 72 },
    titleBounds: { x: 150, y: 336, width: 740, height: 580 },
    subtitleBounds: { x: 150, y: 922, width: 620, height: 82 },
    artworkFrameBounds: { x: 824, y: 336, width: 620, height: 1380 },
    footerBounds: { x: 150, y: 2204, width: 1300, height: 96 },
  },
  palette: {
    background: "#050505",
    surface: "#0d0d0d",
    foreground: "#f4eadc",
    muted: "#b69f86",
    accent: "#ff8b4d",
    cyan: "#8ad0ff",
    border: "rgba(255, 139, 77, 0.42)",
    glow: "rgba(255, 139, 77, 0.15)",
    shadow: "rgba(0, 0, 0, 0.58)",
  },
  typography: {
    mastheadFontFamily: "var(--font-serif)",
    titleFontFamily: "var(--font-serif)",
    metadataFontFamily: "var(--font-mono)",
    mastheadSize: 118,
    titleMinSize: 72,
    titleMaxSize: 100,
    subtitleSize: 34,
    metadataSize: 18,
    mastheadTracking: "-0.055em",
    titleTracking: "-0.055em",
    subtitleTracking: "0.18em",
    metadataTracking: "0.28em",
    titleLineHeight: 0.88,
    subtitleLineHeight: 1.1,
  },
  titleFitBehavior: "wrap-tight",
  minTitleSize: 72,
  maxTitleSize: 116,
  artworkDoctrine: {
    promptVersion: "editorial-cover-v2::1",
    prompt:
      "Create article-specific artwork only. One dominant visual subject, no text baked into the art, no dashboards, no fake statistics, no floating labels, no brand marks, no random UI chrome. Keep the image cinematic, investigative, and coherent with a dark editorial magazine cover.",
    supportingVisualDoctrine: [
      "Use one dominant hero image that reads clearly at thumbnail size.",
      "Favor a restrained investigative tone over decorative cyberpunk clutter.",
      "Supporting visuals may be technical, but never feel like a dashboard.",
    ],
    prohibitedVisualPatterns: [
      "invented statistics",
      "fake UI labels",
      "busy bento grids",
      "multi-panel collage clutter",
      "generic sci-fi neon spikes",
      "watermarked stock-photo styling",
    ],
  },
};
